### ISSUE TITLE
In ops-rosette.rkt identifier `<<' not included in nested require spec

### ISSUE THREAD

**Issue by pmatos** [mangpo/greenthumb#1]
I installed racket 6.5 on Fedora 23 installed rosette using  raco.
Then ran the arm example:

```
$ racket optimize.rkt --hybrid -p -c 16 -t 60 programs/p14_floor_avg_o0.s
/home/pmatos/Projects/greenthumb/ops-rosette.rkt:3:18: only-in: identifier `<<' not included in nested require spec
  at: rosette
  in: (only-in rosette (<< sym/<<) (>>> sym/>>>))
  context...:
   /home/pmatos/INSTALLS/racket/collects/racket/private/reqprov.rkt:438:5
   /home/pmatos/INSTALLS/racket/collects/racket/require-transform.rkt:266:2: expand-import
   /home/pmatos/INSTALLS/racket/collects/racket/private/stxloc.rkt:21:17: try-next
   /home/pmatos/INSTALLS/racket/collects/racket/private/reqprov.rkt:243:2
   /home/pmatos/.racket/6.5/pkgs/rosette/rosette/base/form/module.rkt:16:0
   standard-module-name-resolver
   /home/pmatos/.racket/6.5/pkgs/rosette/rosette/base/form/module.rkt:16:0
   standard-module-name-resolver
   standard-module-name-resolver
   standard-module-name-resolver
```

**Comment by mangpo** [comment]
My apology. I forgot that Rosette just had a new release, and my tool is not compatible with the new version. You should download Rosette 1.1 from https://github.com/emina/rosette/releases/tag/v1.1
Follow README in v1.1. Also, you need to put z3 executable in rosette/bin as well, but you don't need cvc4.

**Comment by pmatos** [comment]
Thank you for your quick reply. I will give the new rosette a try.

**Comment by pmatos** [comment]
It works with Rosette v1.1. Is work on greenthumb stalled?

**Comment by mangpo** [comment]
I'm still maintaining it. Rosette 2.0 is very different from 1.1, so it would take quite a bit of work to make it compatible with Rosette.

There are some features that I want to add to GreenThumb, but it's not my top priority. If you're interested in using it, I'm happy to help and add more features you might need if they are not too difficult. Can you tell me more about what would you like to use GreenThumb for? If you don't want to discuss about the project on github, we can discuss over email. My email is mangpo [at] eecs.berkeley.edu

**Comment by pmatos** [comment]
Thanks. I will send you a private email.
